name: OTF Testing
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Functional Test
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Setup Appium
        run: docker run -d -p 6080:6080 -p 4723:4723 -p 5554:5554 -p 5555:5555 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true -e APPIUM=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_14.0

      - name: Wait for docker
        run: sh wait.sh

      - name: Check the vnc
        run: curl http://localhost:6080

      - name: Install App using ADB
        run: adb install -r -g app-debug.apk

      - name: Install Selenium client
        run: pip install -U selenium Appium-Python-Client

      - name: Run tests using pytest
        run: |
          python tests/rectangle_test.py
          python tests/triangle_test.py

